/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with basic service information.
         */
        get: operations["root_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Detailed health check endpoint with service configuration.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluators
         * @description List all available evaluators grouped by document type.
         *
         *     Returns information about each evaluator including:
         *     - Name
         *     - Source file/module
         *     - Whether it has assertions
         *     - Additional metadata
         *
         *     Useful for discovering what evaluators are available and how to use them.
         */
        get: operations["list_evaluators_api_v1_evaluators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List all available agents grouped by document type.
         *
         *     Returns information about each agent including:
         *     - Name
         *     - Description
         *     - Output schema type
         *     - Additional metadata
         *
         *     Useful for discovering what agents are available for agent-based evaluation.
         */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Document
         * @description Unified evaluation endpoint for both reports and articles.
         *
         *     **Document Types:**
         *     - `report`: R&D activity reports evaluated against Frascati Manual standards
         *     - `article`: Scientific articles evaluated against SMSM publication standards
         *
         *     **Evaluation Methods:**
         *     - `scoring`: Multiple LLM judges score against standardized criteria (0.0-1.0 scale)
         *     - `agent`: Single AI agent provides comprehensive qualitative analysis
         *
         *     **Evaluators:**
         *     - Leave empty to run all evaluators for the document type
         *     - Provide comma-separated list to run specific evaluators (e.g., "novelty_score,rigor_fluid")
         *     - Use `/api/v1/evaluators` endpoint to see available evaluators
         *
         *     **Supported File Formats:**
         *     - `.docx` - Microsoft Word documents
         *     - `.pdf` - PDF documents
         *     - `.doc` - Legacy Word documents
         *     - `.txt` - Plain text files
         *     - `.md` - Markdown files
         *
         *     **Returns:**
         *     - Converted markdown content
         *     - Evaluation results (format depends on evaluation_type)
         *     - Metadata (filename, character count, duration, etc.)
         *     - Unique evaluation ID for reference
         */
        post: operations["evaluate_document_api_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Report
         * @description Evaluate R&D activity report against Frascati Manual standards.
         *
         *     Convenience endpoint equivalent to `/api/v1/evaluate` with `document_type=report`.
         *
         *     See `/api/v1/evaluate` for full documentation.
         */
        post: operations["evaluate_report_api_v1_reports_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Article
         * @description Evaluate scientific article against SMSM publication standards.
         *
         *     Convenience endpoint equivalent to `/api/v1/evaluate` with `document_type=article`.
         *
         *     See `/api/v1/evaluate` for full documentation.
         */
        post: operations["evaluate_article_api_v1_articles_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_evaluate_article_api_v1_articles_evaluate_post */
        Body_evaluate_article_api_v1_articles_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Article document to evaluate (DOCX, PDF, etc.)
             */
            file: string;
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring'
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of evaluators (optional)
             */
            evaluators?: string | null;
        };
        /** Body_evaluate_document_api_v1_evaluate_post */
        Body_evaluate_document_api_v1_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Document file to evaluate (DOCX, PDF, MD, TXT)
             */
            file: string;
            /**
             * Document Type
             * @description Type of document: 'report' or 'article'
             * @enum {string}
             */
            document_type: "report" | "article";
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring' (default)
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of specific evaluators to run (for scoring mode)
             */
            evaluators?: string | null;
            /**
             * Agents
             * @description Comma-separated list of specific agents to run (for agent mode)
             */
            agents?: string | null;
        };
        /** Body_evaluate_report_api_v1_reports_evaluate_post */
        Body_evaluate_report_api_v1_reports_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Report document to evaluate (DOCX, PDF, etc.)
             */
            file: string;
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring'
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of evaluators (optional)
             */
            evaluators?: string | null;
        };
        /**
         * EvaluatorInfo
         * @description Information about an evaluator.
         */
        EvaluatorInfo: {
            /**
             * Name
             * @description Evaluator name
             */
            name: string;
            /**
             * Source
             * @description Source file or module
             */
            source?: string | null;
            /**
             * Has Assertion
             * @description Whether evaluator has assertions
             * @default false
             */
            has_assertion: boolean;
            /**
             * Rubric
             * @description Evaluation instructions/criteria
             */
            rubric?: string | null;
            /**
             * Metadata
             * @description Additional evaluator metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * EvaluatorsListResponse
         * @description Response from /evaluators/list endpoint.
         */
        EvaluatorsListResponse: {
            /**
             * Evaluators
             * @description Evaluators grouped by document type
             */
            evaluators: {
                [key: string]: components["schemas"]["EvaluatorInfo"][];
            };
            /**
             * Total Evaluators
             * @description Total number of evaluators
             */
            total_evaluators: number;
            /**
             * Document Types
             * @description Available document types
             */
            document_types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Response from /health endpoint.
         */
        HealthCheckResponse: {
            /**
             * Status
             * @description Service status
             */
            status: string;
            /**
             * Service
             * @description Service name
             */
            service: string;
            /**
             * Version
             * @description API version
             */
            version: string;
            /**
             * Evaluation Methods
             * @description Available evaluation methods
             */
            evaluation_methods: string[];
            /**
             * Document Types
             * @description Supported document types
             */
            document_types: string[];
            /**
             * Environment
             * @description Current environment
             */
            environment: string;
            /**
             * Authentication Required
             * @description Whether authentication is required
             */
            authentication_required: boolean;
        };
        /**
         * RootResponse
         * @description Response from root endpoint.
         */
        RootResponse: {
            /**
             * Message
             * @description Welcome message
             */
            message: string;
            /**
             * Status
             * @description Service status
             */
            status: string;
            /**
             * Version
             * @description API version
             */
            version: string;
            /**
             * Docs Url
             * @description URL to API documentation
             */
            docs_url: string;
        };
        /**
         * UnifiedEvaluationResponse
         * @description Unified response that can contain either scoring or agent results.
         */
        UnifiedEvaluationResponse: {
            /**
             * Evaluation Id
             * @description Unique evaluation identifier
             */
            evaluation_id: string;
            /**
             * Document Type
             * @description Type of document evaluated
             */
            document_type: string;
            /**
             * Evaluation Type
             * @description Type of evaluation performed
             */
            evaluation_type: string;
            /**
             * Status
             * @description Response status
             * @default success
             */
            status: string;
            /**
             * Markdown Content
             * @description Converted markdown text from document
             */
            markdown_content: string;
            /**
             * Metadata
             * @description Evaluation metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Results
             * @description Evaluation results (format depends on evaluation_type)
             */
            results: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    list_evaluators_api_v1_evaluators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorsListResponse"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    evaluate_document_api_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_document_api_v1_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_report_api_v1_reports_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_report_api_v1_reports_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_article_api_v1_articles_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_article_api_v1_articles_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
