/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with basic service information.
         */
        get: operations["root_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Detailed health check endpoint with service configuration.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cors-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cors Test
         * @description Test endpoint to verify CORS is working correctly.
         */
        get: operations["cors_test_api_cors_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluators
         * @description List active evaluators grouped by document type.
         *
         *     Reads from the DB-backed ``evaluators`` table so picker UIs reflect any
         *     runtime edits made through the settings page. Inactive evaluators are
         *     omitted because they are not selectable for evaluation runs.
         */
        get: operations["list_evaluators_api_v1_evaluators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List all available agents grouped by document type.
         *
         *     Returns information about each agent including:
         *     - Name
         *     - Description
         *     - Output schema type
         *     - Additional metadata
         *
         *     Useful for discovering what agents are available for agent-based evaluation.
         */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Login */
        post: operations["auth_jwt_login_auth_jwt_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Logout */
        post: operations["auth_jwt_logout_auth_jwt_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_users_me_patch"];
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_users__id__patch"];
        trace?: never;
    };
    "/api/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Document
         * @description Unified evaluation endpoint for both reports and articles.
         *
         *     **Document Types:**
         *     - `report`: R&D activity reports evaluated against Frascati Manual standards
         *     - `article`: Scientific articles evaluated against SMSM publication standards
         *
         *     **Evaluation Methods:**
         *     - `scoring`: Multiple LLM judges score against standardized criteria (0.0-1.0 scale)
         *     - `agent`: Single AI agent provides comprehensive qualitative analysis
         *
         *     **Evaluators:**
         *     - Leave empty to run all evaluators for the document type
         *     - Provide comma-separated list to run specific evaluators (e.g., "novelty_score,rigor_fluid")
         *     - Use `/api/v1/evaluators` endpoint to see available evaluators
         *
         *     **Supported File Formats:**
         *     - `.docx` - Microsoft Word documents
         *     - `.pdf` - PDF documents
         *     - `.doc` - Legacy Word documents
         *     - `.txt` - Plain text files
         *     - `.md` - Markdown files
         *
         *     **Returns:**
         *     - Converted markdown content
         *     - Evaluation results (format depends on evaluation_type)
         *     - Metadata (filename, character count, duration, etc.)
         *     - Unique evaluation ID for reference
         */
        post: operations["evaluate_document_api_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Report
         * @description Evaluate R&D activity report against Frascati Manual standards.
         *
         *     Convenience endpoint equivalent to `/api/v1/evaluate` with `document_type=report`.
         *
         *     See `/api/v1/evaluate` for full documentation.
         */
        post: operations["evaluate_report_api_v1_reports_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Article
         * @description Evaluate scientific article against SMSM publication standards.
         *
         *     Convenience endpoint equivalent to `/api/v1/evaluate` with `document_type=article`.
         *
         *     See `/api/v1/evaluate` for full documentation.
         */
        post: operations["evaluate_article_api_v1_articles_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List user's projects with pagination.
         *
         *     Args:
         *         skip: Number of records to skip (default: 0)
         *         limit: Maximum number of records to return (default: 100)
         *         user: Authenticated user
         *         session: Database session
         *
         *     Returns:
         *         List of user's projects with total count
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project.
         *
         *     Args:
         *         request: Project creation request with name and type
         *         user: Authenticated user
         *         session: Database session
         *
         *     Returns:
         *         Created project details
         *
         *     Raises:
         *         HTTPException: If project name already exists
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/scores-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scores Grid
         * @description Return a cross-project grid of latest scoring evaluations.
         *
         *     One row per project owned by the user, columns keyed by evaluator name.
         */
        get: operations["get_scores_grid_api_v1_projects_scores_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get project details by ID.
         *
         *     Args:
         *         project_id: Project ID
         *         session: Database session
         *
         *     Returns:
         *         Project details
         *
         *     Raises:
         *         HTTPException: If project not found
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Delete a project and all its versions.
         *
         *     Args:
         *         project_id: Project ID
         *         session: Database session
         *
         *     Raises:
         *         HTTPException: If project not found
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/marked-good": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Project Marked Good
         * @description Toggle the manual quality-verified flag on a project.
         */
        patch: operations["set_project_marked_good_api_v1_projects__project_id__marked_good_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description List all versions for a project.
         *
         *     Args:
         *         project_id: Project ID
         *         session: Database session
         *
         *     Returns:
         *         List of document versions
         *
         *     Raises:
         *         HTTPException: If project not found
         */
        get: operations["list_versions_api_v1_projects__project_id__versions_get"];
        put?: never;
        /**
         * Upload Version
         * @description Upload a new document version to a project.
         *
         *     Args:
         *         project_id: Project ID
         *         file: Document file to upload
         *         doc_service: Document service (injected)
         *         session: Database session
         *
         *     Returns:
         *         Created document version details
         *
         *     Raises:
         *         HTTPException: If project not found or file processing fails
         */
        post: operations["upload_version_api_v1_projects__project_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Get document version details with markdown content.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID
         *         session: Database session
         *
         *     Returns:
         *         Document version details with markdown content
         *
         *     Raises:
         *         HTTPException: If project or version not found
         */
        get: operations["get_version_api_v1_projects__project_id__versions__version_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Version
         * @description Delete a document version.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID
         *         session: Database session
         *
         *     Raises:
         *         HTTPException: If project or version not found, or if trying to delete the only version
         */
        delete: operations["delete_version_api_v1_projects__project_id__versions__version_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version Markdown
         * @description Get markdown content for a version.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID
         *         session: Database session
         *
         *     Returns:
         *         Plain text markdown content
         *
         *     Raises:
         *         HTTPException: If project or version not found
         */
        get: operations["get_version_markdown_api_v1_projects__project_id__versions__version_id__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}/set-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Active Version
         * @description Set a version as the active version for the project.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID to set as active
         *         session: Database session
         *
         *     Returns:
         *         Updated project details
         *
         *     Raises:
         *         HTTPException: If project or version not found
         */
        post: operations["set_active_version_api_v1_projects__project_id__versions__version_id__set_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Version
         * @description Run evaluation on a document version.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID
         *         evaluation_type: Type of evaluation ("scoring" or "agent")
         *         evaluators: Comma-separated list of evaluators (for scoring)
         *         agents: Comma-separated list of agents (for agent mode)
         *         eval_service: Evaluation service (injected)
         *         session: Database session
         *
         *     Returns:
         *         Evaluation results
         *
         *     Raises:
         *         HTTPException: If project or version not found, or evaluation fails
         */
        post: operations["evaluate_version_api_v1_projects__project_id__versions__version_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}/llm-detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Llm Detection
         * @description Run the LLM-authorship detector agent on an article version.
         *
         *     Thin wrapper around the agent evaluation flow, locked to a single agent
         *     (``llm_detector_agent``) so the frontend can offer it as a one-click action.
         */
        post: operations["run_llm_detection_api_v1_projects__project_id__versions__version_id__llm_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/versions/{version_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Version Evaluations
         * @description List all evaluations for a document version.
         *
         *     Args:
         *         project_id: Project ID
         *         version_id: Version ID
         *         session: Database session
         *
         *     Returns:
         *         List of evaluation history items
         *
         *     Raises:
         *         HTTPException: If project or version not found
         */
        get: operations["list_version_evaluations_api_v1_projects__project_id__versions__version_id__evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation
         * @description Get evaluation details by UUID.
         *
         *     Args:
         *         project_id: Project ID
         *         evaluation_id: Evaluation UUID
         *         session: Database session
         *
         *     Returns:
         *         Evaluation details with full results
         *
         *     Raises:
         *         HTTPException: If project or evaluation not found
         */
        get: operations["get_evaluation_api_v1_projects__project_id__evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluators-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluators
         * @description List all evaluators, optionally filtered by document type / active flag.
         */
        get: operations["list_evaluators_api_v1_evaluators_admin_get"];
        put?: never;
        /**
         * Create Evaluator
         * @description Create a new custom evaluator.
         */
        post: operations["create_evaluator_api_v1_evaluators_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluators-admin/{evaluator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Evaluator
         * @description Delete a custom evaluator. Defaults can only be deactivated, not removed.
         */
        delete: operations["delete_evaluator_api_v1_evaluators_admin__evaluator_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Evaluator
         * @description Update an evaluator. Renaming is only allowed for ``source='custom'`` rows.
         */
        patch: operations["update_evaluator_api_v1_evaluators_admin__evaluator_id__patch"];
        trace?: never;
    };
    "/api/v1/evaluators-admin/{evaluator_id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Active
         * @description Enable or disable an evaluator. Works for both default and custom rows.
         */
        patch: operations["toggle_active_api_v1_evaluators_admin__evaluator_id__active_patch"];
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description Serve the React SPA for all non-API routes.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** Body_auth_jwt_login_auth_jwt_login_post */
        Body_auth_jwt_login_auth_jwt_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_evaluate_article_api_v1_articles_evaluate_post */
        Body_evaluate_article_api_v1_articles_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Article document to evaluate (DOCX, PDF, etc.)
             */
            file: string;
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring'
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of evaluators (optional)
             */
            evaluators?: string | null;
        };
        /** Body_evaluate_document_api_v1_evaluate_post */
        Body_evaluate_document_api_v1_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Document file to evaluate (DOCX, PDF, MD, TXT)
             */
            file: string;
            /**
             * Document Type
             * @description Type of document: 'report' or 'article'
             * @enum {string}
             */
            document_type: "report" | "article";
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring' (default)
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of specific evaluators to run (for scoring mode)
             */
            evaluators?: string | null;
            /**
             * Agents
             * @description Comma-separated list of specific agents to run (for agent mode)
             */
            agents?: string | null;
        };
        /** Body_evaluate_report_api_v1_reports_evaluate_post */
        Body_evaluate_report_api_v1_reports_evaluate_post: {
            /**
             * File
             * Format: binary
             * @description Report document to evaluate (DOCX, PDF, etc.)
             */
            file: string;
            /**
             * Evaluation Type
             * @description Evaluation method: 'agent' or 'scoring'
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /**
             * Evaluators
             * @description Comma-separated list of evaluators (optional)
             */
            evaluators?: string | null;
        };
        /** Body_evaluate_version_api_v1_projects__project_id__versions__version_id__evaluate_post */
        Body_evaluate_version_api_v1_projects__project_id__versions__version_id__evaluate_post: {
            /**
             * Evaluation Type
             * @default scoring
             * @enum {string}
             */
            evaluation_type: "agent" | "scoring";
            /** Evaluators */
            evaluators?: string;
            /** Agents */
            agents?: string;
        };
        /** Body_upload_version_api_v1_projects__project_id__versions_post */
        Body_upload_version_api_v1_projects__project_id__versions_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CreateProjectRequest
         * @description Request to create a new project.
         */
        CreateProjectRequest: {
            /**
             * Name
             * @description Project name (must be unique)
             */
            name: string;
            /**
             * Project Type
             * @description Type of project
             * @enum {string}
             */
            project_type: "straipsnis" | "ataskaita";
        };
        /**
         * DocumentVersionDetailResponse
         * @description Response for a document version with markdown content.
         */
        DocumentVersionDetailResponse: {
            /**
             * Id
             * @description Version ID
             */
            id: number;
            /**
             * Project Id
             * @description Project ID
             */
            project_id: number;
            /**
             * Version Number
             * @description Version number
             */
            version_number: number;
            /**
             * Original Filename
             * @description Original filename
             */
            original_filename: string;
            /**
             * Character Count
             * @description Character count
             */
            character_count: number;
            /**
             * Evaluation Count
             * @description Number of evaluations
             */
            evaluation_count: number;
            /**
             * Is Active
             * @description Whether this is the active version
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Markdown Content
             * @description Markdown content of the document
             */
            markdown_content: string;
        };
        /**
         * DocumentVersionResponse
         * @description Response for a document version.
         */
        DocumentVersionResponse: {
            /**
             * Id
             * @description Version ID
             */
            id: number;
            /**
             * Project Id
             * @description Project ID
             */
            project_id: number;
            /**
             * Version Number
             * @description Version number
             */
            version_number: number;
            /**
             * Original Filename
             * @description Original filename
             */
            original_filename: string;
            /**
             * Character Count
             * @description Character count
             */
            character_count: number;
            /**
             * Evaluation Count
             * @description Number of evaluations
             */
            evaluation_count: number;
            /**
             * Is Active
             * @description Whether this is the active version
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /**
         * EvaluationDetailResponse
         * @description Response for an evaluation with full results.
         */
        EvaluationDetailResponse: {
            /**
             * Id
             * @description Evaluation database ID
             */
            id: number;
            /**
             * Evaluation Id
             * @description Evaluation UUID
             */
            evaluation_id: string;
            /**
             * Evaluation Type
             * @description Type of evaluation
             */
            evaluation_type: string;
            /**
             * Evaluators Used
             * @description List of evaluators used
             */
            evaluators_used: string[];
            /**
             * Status
             * @description Evaluation status
             */
            status: string;
            /**
             * Duration Seconds
             * @description Duration in seconds
             */
            duration_seconds: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Results
             * @description Full evaluation results
             */
            results: {
                [key: string]: unknown;
            };
        };
        /**
         * EvaluationHistoryItem
         * @description Response for an evaluation in history list.
         */
        EvaluationHistoryItem: {
            /**
             * Id
             * @description Evaluation database ID
             */
            id: number;
            /**
             * Evaluation Id
             * @description Evaluation UUID
             */
            evaluation_id: string;
            /**
             * Evaluation Type
             * @description Type of evaluation
             */
            evaluation_type: string;
            /**
             * Evaluators Used
             * @description List of evaluators used
             */
            evaluators_used: string[];
            /**
             * Status
             * @description Evaluation status
             */
            status: string;
            /**
             * Duration Seconds
             * @description Duration in seconds
             */
            duration_seconds: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /** EvaluatorActiveToggle */
        EvaluatorActiveToggle: {
            /** Is Active */
            is_active: boolean;
        };
        /** EvaluatorCreate */
        EvaluatorCreate: {
            /** Name */
            name: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "article" | "report";
            /** Rubric */
            rubric: string;
            /**
             * Has Assertion
             * @default false
             */
            has_assertion: boolean;
        };
        /**
         * EvaluatorInfo
         * @description Information about an evaluator.
         */
        EvaluatorInfo: {
            /**
             * Name
             * @description Evaluator name
             */
            name: string;
            /**
             * Source
             * @description Source file or module
             */
            source?: string | null;
            /**
             * Has Assertion
             * @description Whether evaluator has assertions
             * @default false
             */
            has_assertion: boolean;
            /**
             * Rubric
             * @description Evaluation instructions/criteria
             */
            rubric?: string | null;
            /**
             * Metadata
             * @description Additional evaluator metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * EvaluatorRecord
         * @description Public representation of a stored evaluator.
         */
        EvaluatorRecord: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "article" | "report";
            /** Rubric */
            rubric: string;
            /** Has Assertion */
            has_assertion: boolean;
            /** Is Active */
            is_active: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "default" | "custom";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** EvaluatorUpdate */
        EvaluatorUpdate: {
            /** Name */
            name?: string | null;
            /** Rubric */
            rubric?: string | null;
            /** Has Assertion */
            has_assertion?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * EvaluatorsListResponse
         * @description Response from /evaluators/list endpoint.
         */
        EvaluatorsListResponse: {
            /**
             * Evaluators
             * @description Evaluators grouped by document type
             */
            evaluators: {
                [key: string]: components["schemas"]["EvaluatorInfo"][];
            };
            /**
             * Total Evaluators
             * @description Total number of evaluators
             */
            total_evaluators: number;
            /**
             * Document Types
             * @description Available document types
             */
            document_types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Response from /health endpoint.
         */
        HealthCheckResponse: {
            /**
             * Status
             * @description Service status
             */
            status: string;
            /**
             * Service
             * @description Service name
             */
            service: string;
            /**
             * Version
             * @description API version
             */
            version: string;
            /**
             * Evaluation Methods
             * @description Available evaluation methods
             */
            evaluation_methods: string[];
            /**
             * Document Types
             * @description Supported document types
             */
            document_types: string[];
            /**
             * Environment
             * @description Current environment
             */
            environment: string;
            /**
             * Authentication Required
             * @description Whether authentication is required
             */
            authentication_required: boolean;
        };
        /**
         * MarkedGoodRequest
         * @description Request to toggle the marked-good flag on a project.
         */
        MarkedGoodRequest: {
            /**
             * Value
             * @description True to mark as GOOD, False to unmark
             */
            value: boolean;
        };
        /**
         * ProjectListResponse
         * @description Response for list of projects.
         */
        ProjectListResponse: {
            /**
             * Projects
             * @description List of projects
             */
            projects: components["schemas"]["ProjectResponse"][];
            /**
             * Total
             * @description Total number of projects
             */
            total: number;
        };
        /**
         * ProjectResponse
         * @description Response for a project.
         */
        ProjectResponse: {
            /**
             * Id
             * @description Project ID
             */
            id: number;
            /**
             * Name
             * @description Project name
             */
            name: string;
            /**
             * Project Type
             * @description Project type
             */
            project_type: string;
            /**
             * Active Version Id
             * @description Active version ID
             */
            active_version_id: number | null;
            /**
             * Active Version Number
             * @description Active version number
             */
            active_version_number: number | null;
            /**
             * Total Versions
             * @description Total number of versions
             */
            total_versions: number;
            /**
             * Is Marked Good
             * @description Manually marked as quality-verified
             * @default false
             */
            is_marked_good: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * RootResponse
         * @description Response from root endpoint.
         */
        RootResponse: {
            /**
             * Message
             * @description Welcome message
             */
            message: string;
            /**
             * Status
             * @description Service status
             */
            status: string;
            /**
             * Version
             * @description API version
             */
            version: string;
            /**
             * Docs Url
             * @description URL to API documentation
             */
            docs_url: string;
        };
        /**
         * ScoresGridResponse
         * @description Aggregated scoring grid across all projects of a given type.
         */
        ScoresGridResponse: {
            /**
             * Document Type
             * @description Logical document type
             * @enum {string}
             */
            document_type: "article" | "report";
            /**
             * Project Type
             * @description Underlying project type
             * @enum {string}
             */
            project_type: "straipsnis" | "ataskaita";
            /**
             * Evaluators
             * @description Union of evaluator names appearing in any row
             */
            evaluators: string[];
            /**
             * Rows
             * @description One row per project
             */
            rows: components["schemas"]["ScoresGridRow"][];
        };
        /**
         * ScoresGridRow
         * @description One row in the cross-project scoring grid.
         */
        ScoresGridRow: {
            /**
             * Project Id
             * @description Project ID
             */
            project_id: number;
            /**
             * Project Name
             * @description Project name
             */
            project_name: string;
            /**
             * Project Type
             * @description Project type (straipsnis | ataskaita)
             */
            project_type: string;
            /**
             * Is Marked Good
             * @description Whether the project is manually quality-verified
             */
            is_marked_good: boolean;
            /**
             * Active Version Id
             * @description ID of the active version (if any)
             */
            active_version_id: number | null;
            /**
             * Active Version Number
             * @description Version number of the active version
             */
            active_version_number: number | null;
            /**
             * Evaluation Id
             * @description UUID of the latest scoring evaluation, if any
             */
            evaluation_id: string | null;
            /**
             * Evaluated At
             * @description When the latest scoring evaluation finished
             */
            evaluated_at: string | null;
            /**
             * Scores
             * @description Scores keyed by evaluator name
             */
            scores?: {
                [key: string]: number;
            };
        };
        /**
         * UnifiedEvaluationResponse
         * @description Unified response that can contain either scoring or agent results.
         */
        UnifiedEvaluationResponse: {
            /**
             * Evaluation Id
             * @description Unique evaluation identifier
             */
            evaluation_id: string;
            /**
             * Document Type
             * @description Type of document evaluated
             */
            document_type: string;
            /**
             * Evaluation Type
             * @description Type of evaluation performed
             */
            evaluation_type: string;
            /**
             * Status
             * @description Response status
             * @default success
             */
            status: string;
            /**
             * Markdown Content
             * @description Converted markdown text from document
             */
            markdown_content: string;
            /**
             * Metadata
             * @description Evaluation metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Results
             * @description Evaluation results (format depends on evaluation_type)
             */
            results: {
                [key: string]: unknown;
            };
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
        };
        /**
         * UserRead
         * @description Schema for reading user data.
         */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /**
         * UserUpdate
         * @description Schema for updating user data.
         */
        UserUpdate: {
            /** Password */
            password?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    cors_test_api_cors_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_evaluators_api_v1_evaluators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorsListResponse"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_jwt_login_auth_jwt_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_auth_jwt_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
                     *       "token_type": "bearer"
                     *     }
                     */
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_logout_auth_jwt_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_document_api_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_document_api_v1_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_report_api_v1_reports_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_report_api_v1_reports_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_article_api_v1_articles_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_evaluate_article_api_v1_articles_evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scores_grid_api_v1_projects_scores_grid_get: {
        parameters: {
            query?: {
                document_type?: "article" | "report";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoresGridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_marked_good_api_v1_projects__project_id__marked_good_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkedGoodRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_projects__project_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_version_api_v1_projects__project_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_version_api_v1_projects__project_id__versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_projects__project_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_version_api_v1_projects__project_id__versions__version_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_markdown_api_v1_projects__project_id__versions__version_id__markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_version_api_v1_projects__project_id__versions__version_id__set_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_version_api_v1_projects__project_id__versions__version_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_evaluate_version_api_v1_projects__project_id__versions__version_id__evaluate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_llm_detection_api_v1_projects__project_id__versions__version_id__llm_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_version_evaluations_api_v1_projects__project_id__versions__version_id__evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_v1_projects__project_id__evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluators_api_v1_evaluators_admin_get: {
        parameters: {
            query?: {
                document_type?: ("article" | "report") | null;
                only_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluator_api_v1_evaluators_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluatorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evaluator_api_v1_evaluators_admin__evaluator_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluator_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_evaluator_api_v1_evaluators_admin__evaluator_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluator_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluatorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_active_api_v1_evaluators_admin__evaluator_id__active_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluator_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluatorActiveToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
