/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as SettingsEvaluatorsRouteImport } from './routes/settings.evaluators'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdEvaluationsEvaluationIdRouteImport } from './routes/projects.$projectId.evaluations.$evaluationId'

const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEvaluatorsRoute = SettingsEvaluatorsRouteImport.update({
  id: '/settings/evaluators',
  path: '/settings/evaluators',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEvaluationsEvaluationIdRoute =
  ProjectsProjectIdEvaluationsEvaluationIdRouteImport.update({
    id: '/evaluations/$evaluationId',
    path: '/evaluations/$evaluationId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/scores': typeof ScoresRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/evaluators': typeof SettingsEvaluatorsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluations/$evaluationId': typeof ProjectsProjectIdEvaluationsEvaluationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/scores': typeof ScoresRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/evaluators': typeof SettingsEvaluatorsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluations/$evaluationId': typeof ProjectsProjectIdEvaluationsEvaluationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/scores': typeof ScoresRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/evaluators': typeof SettingsEvaluatorsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluations/$evaluationId': typeof ProjectsProjectIdEvaluationsEvaluationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/auth'
    | '/reports'
    | '/scores'
    | '/projects/$projectId'
    | '/settings/evaluators'
    | '/projects'
    | '/projects/$projectId/evaluations/$evaluationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/auth'
    | '/reports'
    | '/scores'
    | '/projects/$projectId'
    | '/settings/evaluators'
    | '/projects'
    | '/projects/$projectId/evaluations/$evaluationId'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/auth'
    | '/reports'
    | '/scores'
    | '/projects/$projectId'
    | '/settings/evaluators'
    | '/projects/'
    | '/projects/$projectId/evaluations/$evaluationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  AuthRoute: typeof AuthRoute
  ReportsRoute: typeof ReportsRoute
  ScoresRoute: typeof ScoresRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  SettingsEvaluatorsRoute: typeof SettingsEvaluatorsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/evaluators': {
      id: '/settings/evaluators'
      path: '/settings/evaluators'
      fullPath: '/settings/evaluators'
      preLoaderRoute: typeof SettingsEvaluatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/evaluations/$evaluationId': {
      id: '/projects/$projectId/evaluations/$evaluationId'
      path: '/evaluations/$evaluationId'
      fullPath: '/projects/$projectId/evaluations/$evaluationId'
      preLoaderRoute: typeof ProjectsProjectIdEvaluationsEvaluationIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEvaluationsEvaluationIdRoute: typeof ProjectsProjectIdEvaluationsEvaluationIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEvaluationsEvaluationIdRoute:
    ProjectsProjectIdEvaluationsEvaluationIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  AuthRoute: AuthRoute,
  ReportsRoute: ReportsRoute,
  ScoresRoute: ScoresRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  SettingsEvaluatorsRoute: SettingsEvaluatorsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
